### PR TITLE
Fixing #17 issue (+ using marked.js instead of GitHub flavored markdown)

### PR DESCRIPTION
**Pull request by maxleiko**
Here you go :+1:

### CODE REVIEW

**Comment by olegp** [comment]
I'm OK with you using marked, but rather than bundling, can you use the version from npm & update the README accordingly?

**Comment by maxleiko** [comment]
That was my intention in the first place, but marked.js uses  

``` javascript
module.exports = marked;
```

Which gives nothing to RingoJS's require()
So I was kinda forced to hack the thing:  

``` javascript
// ...
if (typeof exports === 'object') {
  module.exports.marked = marked; // l.1156
}
// ...
```

That's why I did not want to use a dependency in `package.json`

**Comment by olegp** [comment]
... and update package.json as well of course.

**Comment by olegp** [comment]
Are you sure the module.exports pattern doesn't work in Ringo? Version 0.9 here.

Just tested by creating file test.js:

```
module.exports = "test";
```

Then from Ringo REPL:

```
>> require('./test')
test
```

So works for me.

**Comment by maxleiko** [comment]
Yep, I was wrong. Just tried after I replied. 
Gonna send another pull request with the fixes.

**Comment by maxleiko** [comment]
Everything seems to be ok with the latest commit.

**Comment by olegp** [comment]
Cool, thanks!

**Comment by olegp** [comment]
Did require one more small change so this would work with common-node: https://github.com/olegp/mcms/commit/bc24f59abbbbdd0928c574e472d951b568851713

**Pull request merged**
